name: cstar_image_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1l
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1
  provider: ^6.0.3
  routemaster: ^1.0.1
  responsive_framework: ^0.2.0
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/homepage/

























