name: cstar_image_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1l
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1
  provider: ^6.0.3
  routemaster: ^1.0.1
  responsive_framework: ^0.2.0
  page_transition: ^2.0.9
  web_smooth_scroll: ^1.0.0
  url_launcher: ^6.1.5
  google_maps_flutter: ^2.1.10
  google_maps_flutter_web: ^0.4.0+1
  custom_info_window: ^1.0.1
  flutter_svg: ^1.1.3
  dropdown_button2: ^1.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/homepage/
    - assets/images/footer/
    - assets/images/SVG/
    - assets/images/personalColor/
    - assets/images/common/
    - assets/images/colorTherapy/
    - assets/images/teachingTool/
    - assets/images/edu/
    - assets/images/certification/

























